### ISSUE TITLE
Help: integrate open RMF with 2 robots

### ISSUE THREAD

**Issue by SuperTunaa** [open-rmf/fleet_adapter_template#12]
Hi @Yadunund, I'm trying to connect a robot simulation with rmf_core using a custom fleet_adapter. It can do this command `ros2 run rmf_demos_tasks dispatch_loop -s p0 -f p1 --use_sim_time` 

I'm trying to add a new robot to fleet_adapter. I update [`config.yaml`](https://github.com/open-rmf/fleet_adapter_template/blob/1fe945a20fcd6424b71f1c8c20600e7e4324c77d/fleet_adapter_template/config.yaml#L60-L72), nav_graph.yaml. but I'm not sure what need to do more or what am I missing. I have an issue with the second robot is called the position of the first robot.

![image](https://user-images.githubusercontent.com/108850210/182764640-8a83c388-59e9-4fbc-a88a-4bdc97f8e5f8.png)

This is a real position.
![image](https://user-images.githubusercontent.com/73490881/182759002-c108614f-fa45-4ceb-8033-f8d76686df49.png)

**Comment by Yadunund** [comment]
This question is far too general and lacking details on technical implementations. So without seeing your code, I can't offer much help as it is not a problem with this template but rather your setup. In particular I would need to see how you implemented the "fleet manager" that communicates with robots in simulation and provides endpoints for your adapter to query.
I'm also assuming when you say "robot simulation", are you referring to one of the `rmf_demos` where robots are powered using the `slotcar` plugin.

But as of recently, all our robots in `rmf_demos` are controlled by a fleet adapter that was implemented using this template. We have an `rmf_demos_fleet_manager` which the adapter communicates to. So what you're trying to do is already achieved in the `rmf_demos` repository. Take a look at the documentation [here](https://github.com/open-rmf/rmf_demos/tree/main/rmf_demos_fleet_adapter) for more information.

**Comment by SuperTunaa** [comment]
Thank you for your  answer.
