### ISSUE TITLE
Does EasyFullControl API work with humble?

### ISSUE THREAD

**Issue by Vortex-TH** [open-rmf/fleet_adapter_template#23]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 22.04

### Open-RMF installation type

Binaries

### Open-RMF version or commit hash

humble

### ROS distribution

Humble

### ROS installation type

Binaries

### Description of the bug

Apparently, the templates are upgraded to make use of the new EasyFullControl API. But when trying to start the fleet adapter with RMF humble, I get the following error:

```
File "/home/user/rmf_ws/install/fleet_adapter_myfleet/lib/python3.10/site-packages/fleet_adapter_myfleet/fleet_adapter.py", line 30, in <module>
    import rmf_adapter.easy_full_control as rmf_easy
ModuleNotFoundError: No module named 'rmf_adapter.easy_full_control'; 'rmf_adapter' is not a package
[ros2run]: Process exited with failure 1
```
Is there a way to make EasyFullControl API work with the (binary) humble RMF installation?
If so, can other fleet adapters (using the old version) still be used at the same time?

### Steps to reproduce the bug

1. Launch RMF (humble version from binaries)
2. Launch custom fleet adapter from current template with EasyFullControl API

**Comment by arjo129** [comment]
This could be my fault as I've not tested against binary distros and gone ahead and merged #22

To answer your question:

> Is there a way to make EasyFullControl API work with the (binary) humble RMF installation?

`sudo apt update && sudo apt upgrade`??

> If so, can other fleet adapters (using the old version) still be used at the same time?

Yes. Older code should work. If you're in shock you can `git checkout 1fe945a` in this repo, this should pull up the older code.

**Comment by Vortex-TH** [comment]
> `sudo apt update && sudo apt upgrade`??

The packages are up to date. My installed version shows:
```
dpkg -s ros-humble-rmf-dev
Version: 0.0.1-1jammy.20230920.014853
```
I would actually like to use the new version as I'm having a hard time integrating custom actions, but it does not seem to be working yet with the binaries.

**Comment by arjo129** [comment]
Yeah. I tested as well, seems like we haven't done a release with the latest changes. If you want to use this new API, I recommend a [source install](https://github.com/open-rmf/rmf).

Note remember to uninstall RMF binaries if you are doing a source install.

**Comment by Yadunund** [comment]
Hi @Vortex-TH ,
The EasyFullControl API is available with the Rolling and Iron binaries of [rmf_ros2](https://github.com/ros/rosdistro/pull/38602). We try to only backport bug fixes to older distros like Humble so I don't expect it to be available on Humble.

**Comment by Yadunund** [comment]
@arjo129 can you make sure the template repo has a `humble` branch that is compatible with the humble binaries? ie checkout commit before [this PR was merged](https://github.com/open-rmf/fleet_adapter_template/pull/22) and push to a new `humble` branch.
