### ISSUE TITLE
[Other issue]: Implement a custom action to the adapter under the humble branch

### ISSUE THREAD

**Issue by RobLevv** [open-rmf/fleet_adapter_template#29]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Hi, I want to add a custom action to my robot. I managed to make it recognized and controlled by open-rmf but i would like to add other capabilities to my fleet. I followed the tutorial on how to do it but when looking for the execute_action function in the fleet adapter, i did not find it in the humble branch whereas in the main branch, the adapter template is refactored and contains the execute_action function needed in the [tutorial](https://osrf.github.io/ros2multirobotbook/integration_fleets_action_tutorial.html)

How can i do that in this version, is there a way to do it without that function, if yes how ? Should I refactor the adapter as in the main branch.

In the README it is said that for humble users, we should checkout to the humble branch does that mean that this feature is not possible ?

Thank you

**Comment by Yadunund** [comment]
If source ROS 2 Humble and build the rest of Open-RMF from source with `main` branches checked out, you should be able to build the `main` branch of this repo.

**Comment by Yadunund** [comment]
Glad to hear that!
