### ISSUE TITLE
Robot diverge from its navigation graph.

### ISSUE THREAD

**Issue by edcogue** [open-rmf/fleet_adapter_template#7]
### Required information:

- Operating system and version:
  - Ubuntu 20.04
- OpenRMF installation type:
  - Binaries
- OpenRMF version or commit hash
  - First version of working in ROS Galactic
- ROS distribution and version:
  - ROS Galactic
- ROS installation type:
  - From Binaries

### Description of the bug
When the adapter is working with any robot it shows an error like this:

The robot has diverged from its navigation graph, currently located at <15.320280, -10.842711, 0.016867> on map [Floor]

Then the robot starts stopping and going to the previous waypoint. I put the correct transformations in config.yaml getting the equivalent coordinate points in traffic editor navgraph and the escenario with a custom simulation. 

### Steps to reproduce the bug
Launch a reduce version of common.launch
Launch custom adapter with python template

**Comment by Emima-J** [comment]
I have the same problem.

**Comment by Yadunund** [comment]
Could you describe the problem in greater detail? It's not clear to me whether you're seeing that printout as soon as a robot gets added to the fleet or it happens while moving between waypoints.

**Comment by Emima-J** [comment]
The error occurs while the robot is moving between the waypoints.
When the robot moves between two waypoints, the robot is lost and the error message is displayed.
Is there a parameter that can be modified to allow a higher divergence threshold?

**Comment by Emima-J** [comment]
The error occurs while the robot is moving between the waypoints.
When the robot moves between two waypoints, the robot is lost and the error message is displayed.
Is there a parameter that can be modified to allow a higher divergence threshold?

**Comment by Yadunund** [comment]
Hmm it is strange if this happens while the robot is moving between waypoints.

Are you able to share the following files with me: 1) navgraph and or building yaml file + png map used by the robot for navigation, 2) The `config.yaml` file for the adapter 3) waypoint name where the robot starts 4) waypoint name where the robot is trying to go (or the exact task request you submitted)

**Comment by Emima-J** [comment]
I have sent you the files by email.

**Comment by Yadunund** [comment]
Closing since the issue was related to traffic lanes overlapping in space but not actually being connected.
