### ISSUE TITLE
Help: integrate open RMF with my robot

### ISSUE THREAD

**Issue by gregoryyts** [open-rmf/fleet_adapter_template#8]
Hi Yadunund. Sorry if this isn't the right place to ask for the support I need (the support guidelines link - https://github.com/open-rmf/rmf/wiki/Support-guidelines -  is redirecting to root repository of Open RMF).

I'm trying to integrate open RMF with a robot that works with ROS1 (I'm also using ros1_bridge), but when I try to run my fleet adapter, the message "ModuleNotFoundError: No module named rmf_fleet_adapter_python.planner" is shown.

I tried reinstalling Open RMF, and no error occurs when I do that (I'm using the branch called "foxy"). Is there something that I'm missing?

Operating system and version:
Ubuntu 20.04
OpenRMF installation type:
Binaries
OpenRMF version or commit hash
First version of working in ROS Foxy
ROS distribution and version:
ROS Foxy
ROS installation type:
Via debian packages

**Comment by Yadunund** [comment]
Hi @gregoryyts

Apologies for the link not working. It should redirect you to our [discussions board ](https://github.com/open-rmf/rmf/discussions) where we help answer questions that users may have. You might want to look through some of the posts there are relevant ones for integrating ROS 1 robots with RMF.

To clarify more on your error,
* Could you share the output of `dpkg -l | grep ros-foxy-rmf*` ?

The `planner` module in the bindings was only added in [this](https://github.com/open-rmf/rmf_ros2/commit/61ca5ed49ea6da626228cbb9051b7458c599e3a8) commit which may not have been backported to the `foxy` version of the rmf_fleet_adapter_python` package. Hence, you are unable to load it.

 We're no longer actively supporting the `foxy` version of RMF so you have a couple of options here:
 1. Switch to the `galactic` version. 
 2. Open a PR to cherry-pick/backport that commit into the `foxy` version. We may also seek your help in blooming a patch
 3. Build RMF from source. This option will ensure you're always using the latest improvements in the code

**Comment by gregoryyts** [comment]
Sure, here's the output:

ii  ros-foxy-rmf-battery                                0.1.1-1focal.20210910.165827          amd64        Package for modelling battery life of robots
ii  ros-foxy-rmf-building-map-msgs                      1.2.0-1focal.20211112.184900          amd64        Messages used to send building maps
ii  ros-foxy-rmf-building-map-tools                     1.4.0-1focal.20211112.192127          amd64        RMF Building map tools
ii  ros-foxy-rmf-building-sim-common                    1.3.0-1focal.20211112.194500          amd64        Common utility functions for Gazebo and ignition building plugins
ii  ros-foxy-rmf-building-sim-gazebo-plugins            1.3.0-1focal.20211119.131931          amd64        Gazebo plugins so that buildings generated by rmf_building_map_tools can talk to the ROS 2-based systems in the rmf_traffic_ros2 package.
ii  ros-foxy-rmf-cmake-uncrustify                       1.2.0-1focal.20210906.142703          amd64        ament_cmake_uncrustify with support for parsing a config file.
ii  ros-foxy-rmf-demos                                  1.3.1-1focal.20211119.123434          amd64        Common launch files for RMF demos
ii  ros-foxy-rmf-demos-assets                           1.3.1-1focal.20210922.171136          amd64        Models and other media used for RMF demos
ii  ros-foxy-rmf-demos-dashboard-resources              1.3.1-1focal.20210922.171137          amd64        Resource pack for RMF dashboard
ii  ros-foxy-rmf-demos-gz                               1.3.1-1focal.20211119.132602          amd64        Launch files for RMF demos using the Gazebo simulator
ii  ros-foxy-rmf-demos-maps                             1.3.1-1focal.20211119.122834          amd64        A package containing demo maps for rmf
ii  ros-foxy-rmf-demos-panel                            1.3.1-1focal.20211112.190213          amd64        Web based RMF Demo Panel
ii  ros-foxy-rmf-demos-tasks                            1.3.1-1focal.20211112.191007          amd64        A package containing scripts for demos
ii  ros-foxy-rmf-dispenser-msgs                         1.4.0-1focal.20211112.184914          amd64        A package containing messages used to interface to dispenser workcells
ii  ros-foxy-rmf-door-msgs                              1.4.0-1focal.20211112.183125          amd64        Messages used to interface to doors
ii  ros-foxy-rmf-fleet-adapter                          1.4.0-1focal.20211112.200713          amd64        Fleet Adapter package for RMF fleets.
ii  ros-foxy-rmf-fleet-msgs                             1.4.0-1focal.20211112.183506          amd64        A package containing messages used to interface to fleet managers
ii  ros-foxy-rmf-ingestor-msgs                          1.4.0-1focal.20211112.185310          amd64        A package containing messages used to interface to ingestor workcells
ii  ros-foxy-rmf-lift-msgs                              1.4.0-1focal.20211112.183037          amd64        Messages used to interface to lifts.
ii  ros-foxy-rmf-robot-sim-common                       1.3.0-1focal.20211112.201251          amd64        Common utility functions for Gazebo and ignition RMF plugins
ii  ros-foxy-rmf-robot-sim-gazebo-plugins               1.3.0-1focal.20211119.131741          amd64        ROS 2 Gazebo plugins for TeleportIngestors, TeleportDispensers and Readonly Objects
ii  ros-foxy-rmf-task                                   1.0.0-1focal.20210913.061628          amd64        Package for managing tasks in the Robotics Middleware Framework
ii  ros-foxy-rmf-task-msgs                              1.4.0-1focal.20211112.185314          amd64        A package containing messages used to specify tasks
ii  ros-foxy-rmf-task-ros2                              1.4.0-1focal.20211112.195706          amd64        A package managing the dispatching of tasks in RMF system.
ii  ros-foxy-rmf-traffic                                1.4.0-1focal.20210910.053721          amd64        Package for managing traffic in the Robotics Middleware Framework
ii  ros-foxy-rmf-traffic-msgs                           1.4.0-1focal.20211112.184921          amd64        A package containing messages used by the RMF traffic management system.
ii  ros-foxy-rmf-traffic-ros2                           1.4.0-1focal.20211112.194546          amd64        A package containing messages used by the RMF traffic management system.
ii  ros-foxy-rmf-utils                                  1.3.0-1focal.20210909.172550          amd64        Simple C++ programming utilities used by Robotics Middleware Framework packages
ii  ros-foxy-rmf-visualization                          1.2.1-1focal.20211112.213416          amd64        Package containing a single launch file to bringup various visualizations
ii  ros-foxy-rmf-visualization-building-systems         1.2.1-1focal.20211112.185707          amd64        A visualizer for doors and lifts
ii  ros-foxy-rmf-visualization-fleet-states             1.2.1-1focal.20211112.192300          amd64        Fleet state visualizer
ii  ros-foxy-rmf-visualization-msgs                     1.2.0-1focal.20211112.183033          amd64        A package containing messages used for visualizations
ii  ros-foxy-rmf-visualization-rviz2-plugins            1.2.1-1focal.20211112.213018          amd64        A package containing RViz2 plugins for RMF
ii  ros-foxy-rmf-visualization-schedule                 1.2.1-1focal.20211112.195605          amd64        A visualizer for trajectories in rmf schedule
ii  ros-foxy-rmw                                        1.0.3-1focal.20211112.180952          amd64        Contains the ROS middleware API.
ii  ros-foxy-rmw-dds-common                             1.0.3-1focal.20211112.182824          amd64        Define a common interface between DDS implementations of ROS middleware.
ii  ros-foxy-rmw-fastrtps-cpp                           1.2.6-1focal.20211112.185808          amd64        Implement the ROS middleware interface using eProsima FastRTPS static code generation in C++.
ii  ros-foxy-rmw-fastrtps-shared-cpp                    1.2.6-1focal.20211112.183201          amd64        Code shared on static and dynamic type support of rmw_fastrtps_cpp.
ii  ros-foxy-rmw-implementation                         1.0.2-1focal.20211112.190156          amd64        The decision which ROS middleware implementation should be used for C++.
ii  ros-foxy-rmw-implementation-cmake                   1.0.3-1focal.20210901.034658          amd64        CMake functions which can discover and enumerate available implementations.



Apparently, my version of RMF is not compatible with the adapter. I wil change to ROS Galactic and build RMF from source to see what happens. Thank you @Yadunund .

**Comment by Yadunund** [comment]
@gregoryyts you could also try the `Galactic` binaries instead. But keep in mind that if you do decide to build from source, make sure to remove all `rmf` related binaries due to a workspace issue that has been documented https://github.com/open-rmf/rmf/issues/99

You can run `sudo apt remove ros-galactic-rmf-*` 
(or replace the `galactic` above with `foxy`)
